#!/bin/bash

npm install -g --verbose --unsafe-perm homebridge-hue
npm install -g --verbose --unsafe-perm homebridge-broadlink-rm
npm install -g --verbose --unsafe-perm homebridge-camera-ffmpeg
npm install -g --verbose --unsafe-perm homebridge-nest
